# ZeRO-3 (shard optimizer states + gradients + parameters)
gradient_accumulation_steps: 4

optimizer:
  type: Adam
  params:
    lr: 0.001
    betas:
        - 0.8
        - 0.999
    eps: 0.00000001
    weight_decay: 0.0000003

zero_optimization:
  stage: 3
  overlap_comm: true
  contiguous_gradients: true
  reduce_scatter: true
  stage3_max_live_parameters: 1000000000         # leave roomy unless you tune
  stage3_max_reuse_distance: 1000000000
  stage3_param_persistence_threshold: 100000
  reduce_bucket_size: 50000000
  allgather_bucket_size: 50000000

gradient_clipping: 1.0
wall_clock_breakdown: true
